services:
  - type: web
    name: my-fastapi-app
    env: python
    buildCommand: "apt-get update && apt-get install -y tesseract-ocr libtesseract-dev && pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 8000"
